# Generated by Django 5.2.5 on 2025-08-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
