# Generated by Django 5.2.5 on 2025-08-29 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="paid_course",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
    ]
