# Generated by Django 5.2.5 on 2025-08-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_paid_course_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
    ]
