# Generated by Django 5.2.5 on 2025-08-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_remove_course_price_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
