# Generated by Django 5.2.5 on 2025-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_alter_course_options_course_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Цена курса"
            ),
        ),
    ]
