name: Django CI/CD Pipeline

on:
  push:
    branches:
      - develop_35.2  # или develop_34.2 — замени, если нужно

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: django-insecure-ci-key
      DEBUG: 'True'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop_35.2'  # или develop_34.2

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ secrets.DEPLOY_DIR }}
            git pull origin main
            source venv/bin/activate || {
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
            }
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart drf-app.service
          EOF